config/routes.rb
Lavish::Application.routes.draw do
  root to: 'bootstrap#new'
  post '/customize' => 'bootstrap#customize', as: :customize
  get '/preview' => "bootstrap#preview", as: :preview
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/bootstrap_controller.rb
require "engines/bootstrap"

class BootstrapController < ApplicationController
  layout "bootstrap"

  ELEMENTS = [
    'body background',
    'disabled input & button background, input addon background, nav & tabs & pagination link hover background, jumbotron background',
    'disabled link color, input placeholder color, dropdown header color, navbar inverse & link color',
    'nav tab link hover color',
    'link color, primary button background, pagination active background, progress bar background, label background, panel heading color',
    'text color, legend color, dropdown link color, panel text color, code color',
    'navbar inverse background'
  ]

  def new
    @url = params[:image_url].presence || ActionController::Base.helpers.asset_path("default.jpg")
    @colors = Engines::Bootstrap.extract_colors(params[:image_url])

    compile
  end

  def preview
    compile
  end

  def customize
    compile
  end

  private

  def compile
    parse_colors

    engine = Engines::Bootstrap.new(@colors)
    @variables = engine.variables
    @lavishCSS = engine.compile
  end

  def parse_colors
    @colors ||= if params[:colors].present?
      params[:colors].map { |color| color.match(/^#/) ? color : "##{color}" }
    else
      Engines::Bootstrap::DEFAULT_COLORS
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def navbar_active?(name)
    if params[:action] == name
      "active"
    else
      ""
    end
  end
end

app/views/bootstrap/_dropdown.html.erb
<div class="btn-group">
 	<button type="button" class="btn btn-default">
  	<span class='selected-color' style="background-color:<%= colors[index] %>;"></span> <%= colors[index] %>
	</button>
  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
    <span class="caret"></span>
  </button>
  <ul class="dropdown-menu" role="menu">
    <% colors.each do |color| %>
			<li>
				<a href='#' class='select-color' data-index="<%= index %>">
					<span style="display:inline-block;width:20px;height:15px;background-color:<%= color %>;"></span>
					<span class='value'><%= color%></span>
				</a>
			</li>
		<% end %>
  </ul>
</div>

app/views/bootstrap/customize.js.erb
window.lavishVariables = "<%=raw j @variables %>";
window.lavishCSS = "<%=raw j @lavishCSS %>";
insertLavish(lavishCSS);
$("a.preview-link").prop("href", "<%=j URI.escape preview_path(colors: @colors) %>");

app/views/bootstrap/new.html.erb
<div class="jumbotron">
  <h1>Lavish, Bootstrap like a King</h1>
  <p>Generate your own Bootstrap color scheme from an image and customize to your taste</p>
  <p style="font-weight:bold;text-align:center;">Now compatible with Bootstrap 3.3.4</p>
  <div style="text-align:center;">
    <a href='https://github.com/mquan/lavish' class='btn btn-lg btn-default' style="margin-right: 10px;">Github Page</a>
    <%= link_to "Live Preview", preview_path(colors: @colors), class: "btn btn-lg btn-primary preview-link" %>
  </div>
</div>

<div class="page-header">
  <h2>Step 1: Provide an image</h2>
</div>
<div class="row">
  <div class="col-md-12">
    <%= form_tag('/', class: 'form-inline', method: 'get') do %>
      <div class="form-group col-md-8">
        <%= text_field_tag :image_url, @url, placeholder: "Enter image URL", class: 'form-control input-lg', style: 'width: 100%' %>
      </div>
      <%= submit_tag "Go Lavish", class: 'btn btn-lg btn-primary' %>
    <% end %>
  </div>

  <div class="col-md-12" style="margin-top:20px;">
    <div class='col-md-5'><%= image_tag(@url, {:class => 'lavish-image'}) %></div>
    <div class="col-md-7 palette">
      <% last_color = @colors[@colors.length-1] %>
      <% @colors.each_with_index do |c, i| %>
        <div class='color' style="background-color:<%= c%>;border-top:1px solid <%= last_color%>;border-bottom:1px solid <%= last_color%>;<%= %{border-left:1px solid #{last_color};} if i == 0 %>"><%= c %></div>
      <% end %>
    </div>
  </div>
</div>

<div class="page-header">
  <h2>Step 2: Customize everything</h2>
</div>
<div class="row">
  <div class="col-md-12">
    <%= form_tag customize_path, remote: true, id: 'customize-form' do %>
      <table class='table table-bordered'>
        <% @colors.each_with_index do |color, index| %>
          <tr>
            <td class="col-md-6"><%= BootstrapController::ELEMENTS[index]%></td>
            <td class="col-md-3" style="text-align:center;"><%= render :partial => 'dropdown', :locals => { :colors => @colors, :index => index } %></td>
            <td class="col-md-3" style="text-align:center;"><%= text_field_tag "colors[]", color, class: 'form-control jscolor', data: {index: index } %></td>
          </tr>
        <% end %>
      </table>
    <% end %>
  </div>
</div>

<div class="page-header">
  <h2>Step 3: Get the code</h2>
</div>
<div class="row">
  <form>
    <div class="col-md-6">
      <h3>CSS</h3>
      <%=raw text_area_tag :css, @lavishCSS, rows: 15, id: 'css-code', class: 'form-control' %>
      <a href="#" id="css-download" class="btn btn-lg btn-success btn-download">Download lavish-bootstrap.css</a>
    </div>
    <div class="col-md-6">
      <h3>SASS</h3>
      <%=raw text_area_tag :sass, @variables, rows: 15, id: 'sass-code', class: 'form-control' %>
      <a href="#" id="variables-download" class="btn btn-lg btn-success btn-download">Download variables.scss</a>
    </div>
  </form>
</div>

<script type="text/javascript">
  window.lavishVariables = "<%=raw j @variables %>";
</script>
<% samples = [
  {img: "http://design-seeds.com/palettes/CreatureTones510.png", url: "http://design-seeds.com/index.php/home/entry/creature-tones1"},
  {img: "http://design-seeds.com/palettes/SlicedColor510.png", url: "http://design-seeds.com/index.php/home/entry/sliced-color"},
  {img: "http://design-seeds.com/palettes/FloatingColor500-1.png", url: "http://design-seeds.com/index.php/home/entry/floating-color"},
  {img: "http://design-seeds.com/palettes/12/SpringTones505.jpg", url: "http://design-seeds.com/index.php/home/entry/spring-tones3"},
  {img: "http://design-seeds.com/palettes/GrassColor510.png", url: "http://design-seeds.com/index.php/home/entry/grass-color"},
  {img: "http://design-seeds.com/palettes/PenciledPalette.png", url: "http://design-seeds.com/index.php/home/entry/penciled-palette"},
  {img: "http://design-seeds.com/palettes/MineralHues_3.png", url: "http://design-seeds.com/index.php/home/entry/mineral-hues4"},
  {img: "http://design-seeds.com/palettes/SeaTones_1.png", url: "http://design-seeds.com/index.php/home/entry/sea-tones1"},
  {img: "http://design-seeds.com/palettes/CockatooColor500.png", url: "http://design-seeds.com/index.php/home/entry/cockatoo-color"}
]%>
<div class="page-header">
  <h2>Want more samples?</h2>
</div>

<div class="row">
  <% samples.each do |sample| %>
    <div class="col-md-4 sample-container">
      <div class="thumbnail">
        <%= link_to image_tag(sample[:img]), sample[:url], class: "image-link" %>
        <div class="caption">
          <a class="btn btn-success" href="/?image_url=<%= sample[:img] %>">Use this &raquo;</a>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/bootstrap/preview.html.erb
<!-- Main jumbotron for a primary marketing message or call to action -->
<div class="jumbotron">
  <h1>Hello, world!</h1>
  <p>This is a template for a simple marketing or informational website. It includes a large callout called the hero unit and three supporting pieces of content. Use it as a starting point to create something more unique.</p>
  <p><a class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>



<div class="page-header">
  <h1>Buttons</h1>
</div>
<p>
  <button type="button" class="btn btn-lg btn-default">Default</button>
  <button type="button" class="btn btn-lg btn-primary">Primary</button>
  <button type="button" class="btn btn-lg btn-success">Success</button>
  <button type="button" class="btn btn-lg btn-info">Info</button>
  <button type="button" class="btn btn-lg btn-warning">Warning</button>
  <button type="button" class="btn btn-lg btn-danger">Danger</button>
  <button type="button" class="btn btn-lg btn-link">Link</button>
</p>
<p>
  <button type="button" class="btn btn-default">Default</button>
  <button type="button" class="btn btn-primary">Primary</button>
  <button type="button" class="btn btn-success">Success</button>
  <button type="button" class="btn btn-info">Info</button>
  <button type="button" class="btn btn-warning">Warning</button>
  <button type="button" class="btn btn-danger">Danger</button>
  <button type="button" class="btn btn-link">Link</button>
</p>
<p>
  <button type="button" class="btn btn-sm btn-default">Default</button>
  <button type="button" class="btn btn-sm btn-primary">Primary</button>
  <button type="button" class="btn btn-sm btn-success">Success</button>
  <button type="button" class="btn btn-sm btn-info">Info</button>
  <button type="button" class="btn btn-sm btn-warning">Warning</button>
  <button type="button" class="btn btn-sm btn-danger">Danger</button>
  <button type="button" class="btn btn-sm btn-link">Link</button>
</p>
<p>
  <button type="button" class="btn btn-xs btn-default">Default</button>
  <button type="button" class="btn btn-xs btn-primary">Primary</button>
  <button type="button" class="btn btn-xs btn-success">Success</button>
  <button type="button" class="btn btn-xs btn-info">Info</button>
  <button type="button" class="btn btn-xs btn-warning">Warning</button>
  <button type="button" class="btn btn-xs btn-danger">Danger</button>
  <button type="button" class="btn btn-xs btn-link">Link</button>
</p>



<div class="page-header">
  <h1>Thumbnails</h1>
</div>
<img data-src="holder.js/200x200" src="/assets/200x200.png" class="img-thumbnail" alt="A generic square placeholder image with a white border around it, making it resemble a photograph taken with an old instant camera" style="width: 200px; height: 200px;">

<!--
<div class="page-header">
  <h1>Dropdown menus</h1>
</div>

<div class="dropdown theme-dropdown clearfix">
  <a id="dropdownMenu1" href="#" role="button" class="sr-only dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
  <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
    <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Action</a></li>
    <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Another action</a></li>
    <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Something else here</a></li>
    <li role="presentation" class="divider"></li>
    <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Separated link</a></li>
  </ul>
</div>
-->

<div class="page-header">
  <h1>Navbars</h1>
</div>

<div class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Project name</a>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Home</a></li>
        <li><a href="#about">About</a></li>
        <li><a href="#contact">Contact</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li class="dropdown-header">Nav header</li>
            <li><a href="#">Separated link</a></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="../navbar/">Default</a></li>
        <li><a href="../navbar-static-top/">Static top</a></li>
        <li class="active"><a href="./">Fixed top</a></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</div>

<div class="navbar navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Project name</a>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Home</a></li>
        <li><a href="#about">About</a></li>
        <li><a href="#contact">Contact</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li class="dropdown-header">Nav header</li>
            <li><a href="#">Separated link</a></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="../navbar/">Default</a></li>
        <li><a href="../navbar-static-top/">Static top</a></li>
        <li class="active"><a href="./">Fixed top</a></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</div>



<div class="page-header">
  <h1>Alerts</h1>
</div>
<div class="alert alert-success">
  <strong>Well done!</strong> You successfully read this important alert message.
</div>
<div class="alert alert-info">
  <strong>Heads up!</strong> This alert needs your attention, but it's not super important.
</div>
<div class="alert alert-warning">
  <strong>Warning!</strong> Best check yo self, you're not looking too good.
</div>
<div class="alert alert-danger">
  <strong>Oh snap!</strong> Change a few things up and try submitting again.
</div>



<div class="page-header">
  <h1>Progress bars</h1>
</div>
<div class="progress">
  <div class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%;"><span class="sr-only">60% Complete</span></div>
</div>
<div class="progress">
  <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 40%"><span class="sr-only">40% Complete (success)</span></div>
</div>
<div class="progress">
  <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100" style="width: 20%"><span class="sr-only">20% Complete</span></div>
</div>
<div class="progress">
  <div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%"><span class="sr-only">60% Complete (warning)</span></div>
</div>
<div class="progress">
  <div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100" style="width: 80%"><span class="sr-only">80% Complete (danger)</span></div>
</div>
<div class="progress">
  <div class="progress-bar progress-bar-success" style="width: 35%"><span class="sr-only">35% Complete (success)</span></div>
  <div class="progress-bar progress-bar-warning" style="width: 20%"><span class="sr-only">20% Complete (warning)</span></div>
  <div class="progress-bar progress-bar-danger" style="width: 10%"><span class='sr-only'>10% Complete (danger)</span></div>
</div>



<div class="page-header">
  <h1>List groups</h1>
</div>
<div class="row">
  <div class="col-sm-4">
    <ul class="list-group">
      <li class="list-group-item">Cras justo odio</li>
      <li class="list-group-item">Dapibus ac facilisis in</li>
      <li class="list-group-item">Morbi leo risus</li>
      <li class="list-group-item">Porta ac consectetur ac</li>
      <li class="list-group-item">Vestibulum at eros</li>
    </ul>
  </div><!-- /.col-sm-4 -->
  <div class="col-sm-4">
    <div class="list-group">
      <a href="#" class="list-group-item active">
        Cras justo odio
      </a>
      <a href="#" class="list-group-item">Dapibus ac facilisis in</a>
      <a href="#" class="list-group-item">Morbi leo risus</a>
      <a href="#" class="list-group-item">Porta ac consectetur ac</a>
      <a href="#" class="list-group-item">Vestibulum at eros</a>
    </div>
  </div><!-- /.col-sm-4 -->
  <div class="col-sm-4">
    <div class="list-group">
      <a href="#" class="list-group-item active">
        <h4 class="list-group-item-heading">List group item heading</h4>
        <p class="list-group-item-text">Donec id elit non mi porta gravida at eget metus. Maecenas sed diam eget risus varius blandit.</p>
      </a>
      <a href="#" class="list-group-item">
        <h4 class="list-group-item-heading">List group item heading</h4>
        <p class="list-group-item-text">Donec id elit non mi porta gravida at eget metus. Maecenas sed diam eget risus varius blandit.</p>
      </a>
      <a href="#" class="list-group-item">
        <h4 class="list-group-item-heading">List group item heading</h4>
        <p class="list-group-item-text">Donec id elit non mi porta gravida at eget metus. Maecenas sed diam eget risus varius blandit.</p>
      </a>
    </div>
  </div><!-- /.col-sm-4 -->
</div>



<div class="page-header">
  <h1>Panels</h1>
</div>
<div class="row">
  <div class="col-sm-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Panel title</h3>
      </div>
      <div class="panel-body">
        Panel content
      </div>
    </div>
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title">Panel title</h3>
      </div>
      <div class="panel-body">
        Panel content
      </div>
    </div>
  </div><!-- /.col-sm-4 -->
  <div class="col-sm-4">
    <div class="panel panel-success">
      <div class="panel-heading">
        <h3 class="panel-title">Panel title</h3>
      </div>
      <div class="panel-body">
        Panel content
      </div>
    </div>
    <div class="panel panel-info">
      <div class="panel-heading">
        <h3 class="panel-title">Panel title</h3>
      </div>
      <div class="panel-body">
        Panel content
      </div>
    </div>
  </div><!-- /.col-sm-4 -->
  <div class="col-sm-4">
    <div class="panel panel-warning">
      <div class="panel-heading">
        <h3 class="panel-title">Panel title</h3>
      </div>
      <div class="panel-body">
        Panel content
      </div>
    </div>
    <div class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title">Panel title</h3>
      </div>
      <div class="panel-body">
        Panel content
      </div>
    </div>
  </div><!-- /.col-sm-4 -->
</div>



<div class="page-header">
  <h1>Wells</h1>
</div>
<div class="well">
  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sed diam eget risus varius blandit sit amet non magna. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent commodo cursus magna, vel scelerisque nisl consectetur et. Cras mattis consectetur purus sit amet fermentum. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Aenean lacinia bibendum nulla sed consectetur.</p>
</div>

app/views/layouts/bootstrap.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lavish - Generate your own Bootstrap color scheme</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <style id='lavish-style' type="text/css"><%=raw @lavishCSS %></style>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Lavish</a>
      </div>
      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <li class="<%= navbar_active?('new')%>"><a href="/">Home</a></li>
          <li class="<%= navbar_active?('preview')%>"><%= link_to 'Preview', preview_path(colors: @colors), class: 'preview-link' %></li>
        </ul>
      </div>
    </div>
  </div>

  <div class="container">
    <%= yield %>

    <div class="spinner-container">
      <div class="shade"></div>
      <div class="main">
        <div id="spinner"></div>
        <div class="caption">Mixing colors...</div>
      </div>
    </div>

    <hr>
    <footer>
      <p>;-) A side project by <a href="https://github.com/mquan">Quan</a></p>
    </footer>
  </div>

  <script type="text/javascript">
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-12037604-8']);
    _gaq.push(['_trackPageview']);

    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();
  </script>
</body>
</html>